version: '3.8'

services:
  todolist:
    image: 891612543902.dkr.ecr.us-east-1.amazonaws.com/backend-repo:latest
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      RDS_SECRET_NAME: todo-rds-db
    networks:
      - app-network

  frontend:
    image: 891612543902.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:latest
    ports:
      - "3000:80"
    depends_on:
      - todolist
    networks:
      - app-network

networks:
  app-network:
